// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionorDetailAPI.Models;

namespace PensionorDetailAPI.Migrations
{
    [DbContext(typeof(PensionManagementDBContext))]
    [Migration("20210929162358_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PensionorDetailAPI.Models.PensionTransaction", b =>
                {
                    b.Property<int>("TransactionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadhaarNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("BankType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PAN");

                    b.Property<double?>("PensionAmount")
                        .HasColumnType("float");

                    b.Property<int?>("PensionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("TransactionNum")
                        .HasName("PK__PensionT__829367DA2E88EE74");

                    b.HasIndex("AadhaarNo");

                    b.ToTable("PensionTransaction");
                });

            modelBuilder.Entity("PensionorDetailAPI.Models.PensionerDetail", b =>
                {
                    b.Property<string>("AadhaarNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<double?>("Allowance")
                        .HasColumnType("float");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("BankType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PAN");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PensionType")
                        .HasColumnType("int");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.HasKey("AadhaarNo")
                        .HasName("PK__Pensione__6F3B29F7307713C9");

                    b.ToTable("PensionerDetail");
                });

            modelBuilder.Entity("PensionorDetailAPI.Models.PensionTransaction", b =>
                {
                    b.HasOne("PensionorDetailAPI.Models.PensionerDetail", "AadhaarNoNavigation")
                        .WithMany("PensionTransactions")
                        .HasForeignKey("AadhaarNo")
                        .HasConstraintName("FK__PensionTr__Aadha__398D8EEE");

                    b.Navigation("AadhaarNoNavigation");
                });

            modelBuilder.Entity("PensionorDetailAPI.Models.PensionerDetail", b =>
                {
                    b.Navigation("PensionTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
